"""capture missing model changes

Revision ID: 0f44e391b8bb
Revises: e98d5f9be5d8
Create Date: 2026-03-15 18:50:17.957329

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f44e391b8bb'
down_revision: Union[str, None] = 'e98d5f9be5d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_habit_logs_habit_date', 'habit_logs', ['habit_id', 'date'], unique=False)
    op.create_index('idx_tasks_project_parent', 'tasks', ['project_id', 'parent_id'], unique=False)
    op.create_index('idx_workout_day_exercises_tmpl_ordinal', 'workout_day_exercises', ['template_id', 'ordinal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workout_day_exercises_tmpl_ordinal', table_name='workout_day_exercises')
    op.drop_index('idx_tasks_project_parent', table_name='tasks')
    op.drop_index('idx_habit_logs_habit_date', table_name='habit_logs')
    # ### end Alembic commands ###
