"""add_training_progression

Revision ID: 1690f6d32f74
Revises: 004
Create Date: 2026-03-06 00:00:39.457145

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1690f6d32f74'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_progressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_progressions_exercise_id'), 'training_progressions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_training_progressions_id'), 'training_progressions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_progressions_id'), table_name='training_progressions')
    op.drop_index(op.f('ix_training_progressions_exercise_id'), table_name='training_progressions')
    op.drop_table('training_progressions')
    # ### end Alembic commands ###
