"""Sync schema and add is_active and custom_name

Revision ID: 2275dcb486d3
Revises: 0f44e391b8bb
Create Date: 2026-03-15 19:35:17.642353

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2275dcb486d3'
down_revision: Union[str, None] = '0f44e391b8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
