"""complete_relational_migration

Revision ID: 760fc49c5bc0
Revises: 7cb28b9f0f1a
Create Date: 2026-03-17 12:37:31.456390

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '760fc49c5bc0'
down_revision: Union[str, None] = '7cb28b9f0f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_completion_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_completion_log'))
    )
    op.create_index(op.f('ix_daily_completion_log_date'), 'daily_completion_log', ['date'], unique=True)
    op.create_index(op.f('ix_daily_completion_log_id'), 'daily_completion_log', ['id'], unique=False)
    op.create_table('life_goal_tiers',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('emoji', sa.String(length=16), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('collapsed', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_life_goal_tiers'))
    )
    op.create_table('prayer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('prayer_name', sa.String(length=64), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prayer_logs'))
    )
    op.create_index('idx_prayer_logs_date_name', 'prayer_logs', ['date', 'prayer_name'], unique=False)
    op.create_index(op.f('ix_prayer_logs_date'), 'prayer_logs', ['date'], unique=False)
    op.create_index(op.f('ix_prayer_logs_id'), 'prayer_logs', ['id'], unique=False)
    op.create_table('top3_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('quick_task_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('done', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_top3_items'))
    )
    op.create_index('idx_top3_items_slot', 'top3_items', ['slot'], unique=True)
    op.create_index(op.f('ix_top3_items_id'), 'top3_items', ['id'], unique=False)
    op.create_table('life_goals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tier_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('done', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.String(length=10), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['life_goal_tiers.id'], name=op.f('fk_life_goals_tier_id_life_goal_tiers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_life_goals'))
    )
    op.create_index(op.f('ix_life_goals_tier_id'), 'life_goals', ['tier_id'], unique=False)
    op.add_column('projects', sa.Column('ordinal', sa.Integer(), nullable=True))
    op.add_column('quick_tasks', sa.Column('ordinal', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('ordinal', sa.Integer(), nullable=True))
    op.create_index('idx_tasks_project_ordinal', 'tasks', ['project_id', 'ordinal'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_project_ordinal', table_name='tasks')
    op.drop_column('tasks', 'ordinal')
    op.drop_column('quick_tasks', 'ordinal')
    op.drop_column('projects', 'ordinal')
    op.drop_index(op.f('ix_life_goals_tier_id'), table_name='life_goals')
    op.drop_table('life_goals')
    op.drop_index(op.f('ix_top3_items_id'), table_name='top3_items')
    op.drop_index('idx_top3_items_slot', table_name='top3_items')
    op.drop_table('top3_items')
    op.drop_index(op.f('ix_prayer_logs_id'), table_name='prayer_logs')
    op.drop_index(op.f('ix_prayer_logs_date'), table_name='prayer_logs')
    op.drop_index('idx_prayer_logs_date_name', table_name='prayer_logs')
    op.drop_table('prayer_logs')
    op.drop_table('life_goal_tiers')
    op.drop_index(op.f('ix_daily_completion_log_id'), table_name='daily_completion_log')
    op.drop_index(op.f('ix_daily_completion_log_date'), table_name='daily_completion_log')
    op.drop_table('daily_completion_log')
    # ### end Alembic commands ###
