"""naming_convention

Revision ID: 7cb28b9f0f1a
Revises: 2275dcb486d3
Create Date: 2026-03-15 20:16:02.014464

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb28b9f0f1a'
down_revision: Union[str, None] = '2275dcb486d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
