"""add_daily_stats

Revision ID: 8d296e8b25ed
Revises: 760fc49c5bc0
Create Date: 2026-03-17 12:52:50.463261

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d296e8b25ed'
down_revision: Union[str, None] = '760fc49c5bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('focus_score', sa.Float(), nullable=True),
    sa.Column('habit_streak', sa.Integer(), nullable=True),
    sa.Column('top3_done_count', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_stats'))
    )
    op.create_index(op.f('ix_daily_stats_date'), 'daily_stats', ['date'], unique=True)
    op.create_index(op.f('ix_daily_stats_id'), 'daily_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_stats_id'), table_name='daily_stats')
    op.drop_index(op.f('ix_daily_stats_date'), table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
