"""add_daily_schedule

Revision ID: e98d5f9be5d8
Revises: 1690f6d32f74
Create Date: 2026-03-06 20:58:19.007541

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98d5f9be5d8'
down_revision: Union[str, None] = '1690f6d32f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('is_completed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workout_day_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_schedules_date'), 'daily_schedules', ['date'], unique=True)
    op.create_index(op.f('ix_daily_schedules_id'), 'daily_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_schedules_id'), table_name='daily_schedules')
    op.drop_index(op.f('ix_daily_schedules_date'), table_name='daily_schedules')
    op.drop_table('daily_schedules')
    # ### end Alembic commands ###
